export const FABRIC_SETTINGS = {
  CANVAS_HEIGHT: 518,
  CANVAS_WIDTH: 970,
  CANVAS_BACKGROUND: "#fff",
  CORNER_SIZE: 8,
  CORNER_STYLE: "circle",
  SELECTION_COLOR: "rgba(232, 248, 255, 0.1)",
  SELECTION_BORDER_COLOR: "#cef0fe",
  SELECTION_LINE_WIDTH: 1,
  START_COLOR: "#ff0000",
};

export const CANVAS_SETTINGS = {
  height: FABRIC_SETTINGS.CANVAS_HEIGHT,
  width: FABRIC_SETTINGS.CANVAS_WIDTH,
  backgroundColor: FABRIC_SETTINGS.CANVAS_BACKGROUND,
};
